name = "25jh"
compatibility_date = "2026-07-22"
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "FILES"
bucket_name = "25jh-files"

[[d1_databases]]
binding = "DB"
database_name = "25jh-app"
database_id = "8d089715-8e9d-4645-83f7-28547d00f778"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "jh25-passages"
